CREATE TYPE "public"."hackathon_status" AS ENUM('pending', 'confirmed');--> statement-breakpoint
CREATE TABLE "hackathons" (
	"id" text PRIMARY KEY NOT NULL,
	"status" "hackathon_status" DEFAULT 'pending' NOT NULL,
	"company_name" text NOT NULL,
	"contact_name" text NOT NULL,
	"contact_email" text NOT NULL,
	"contact_phone" text NOT NULL,
	"capacity" integer NOT NULL,
	"venue_provided" boolean NOT NULL,
	"equipment" text NOT NULL,
	"lunch" text NOT NULL,
	"custom_lunch" text DEFAULT '' NOT NULL,
	"tool_provision" text NOT NULL,
	"coding_tools" jsonb NOT NULL,
	"custom_coding_tool" text DEFAULT '' NOT NULL,
	"address" jsonb NOT NULL,
	"preferred_event_date" date NOT NULL,
	"consultation_slot" timestamp with time zone NOT NULL,
	"base_price" integer NOT NULL,
	"venue_surcharge" integer NOT NULL,
	"lunch_adjustment" integer NOT NULL,
	"tools_adjustment" integer NOT NULL,
	"total_price" integer NOT NULL,
	"booking_uid" text,
	"booking_ics_uid" text,
	"booking_title" text,
	"booking_start" timestamp with time zone,
	"booking_end" timestamp with time zone,
	"meeting_url" text,
	"demo_mode" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "hackathons_id_format_check" CHECK ("hackathons"."id" ~ '^H[A-Z0-9]{2}-[A-Z0-9]{3}-[A-Z0-9]{3}$'),
	CONSTRAINT "hackathons_capacity_check" CHECK ("hackathons"."capacity" in (15, 30, 50))
);
